version: 2

sources:
  - name: raw
    description: Raw account value data
    database: banking
    schema: raw

    tables:
      - name: account_values
        description: Raw daily account value data for client accounts
        columns: 
          - name: account_id
            description: AccountId
            tests:
              - not_null
              - relationships:
                  to: ref('accounts_snapshot')
                  field: account_id
          - name: value_at_close
            description: Account value at close
            tests:
              - not_null
          - name: as_of_date
            description: Date
            tests:
              - not_null